a, b = input('숫자 두 개를 입력하세요: ').split()
a = int(a)
b = int(b)
print('덧셈은 : ', a + b)
print('뺄셈은 : ', a - b)
print('곱셈은 : ', a * b)
print('나눗셈은 : ', a / b)
print('몫은 : ', a // b)
print('나머지는 : ', a % b)